### ISSUE TITLE
TTL target support stopped working

### ISSUE THREAD

**Issue by p-knaulksmeg** [flar2/wahoo#1]
Since 3.0 kernel builds TTL target support dissapeared. Please return this feature.

![androidfixttl3](https://user-images.githubusercontent.com/47440761/61147491-1ea35f00-a4e5-11e9-81f7-3a20f8ce802e.png)

**Comment by redondo-se** [comment]
I have also run into this. I'd greatly appreciate if you could release a build with this included.

**Comment by p-knaulksmeg** [comment]
Finally we got this since 3.06, thanks.
